# Nome do Workflow
name: Generate Snake

# Define quando a Action vai rodar: a cada 12 horas ou manualmente
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      - uses: Platane/snk@v3
        id: snake-gif
        with:
        
          github_user_name: ${{ github.repository_owner }}
           
          palette: github-dark 
          locale: pt-BR
          color_snake: "#007BFF"
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark

      - name: Push snake animation
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
